{
  "sum.py::test_sum_positive_ShouldThrowException_WhenNegativeArguments2": true
}